# Generated by Django 3.2.7 on 2021-09-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='listings', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.user'),
        ),
    ]
