# Generated by Django 3.2.7 on 2021-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210927_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='listings', to='auctions.Category'),
        ),
    ]
