# Generated by Django 3.2.9 on 2021-11-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_recipe_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
